name: Running custom actions

on: [push]

env: 
  DAY_OF_WEEK: Monday

jobs:
  greeting_job: # name of the job
    runs-on: centos8-runner
    
    env:
      Greeting: Hello
      
    steps:
      - name: "Say hello Monda it's monday"
        run: echo "$Greeting $First_Name. Today is $DAY_OF_WEEK"
        env:
          First_Name: Mona
          
      - name: Access env variables using the env context
        if: ${{ env.DAY_OF_WEEK == 'Monday' }}
        run: echo "$Greeting $First_Name. Today is $DAY_OF_WEEK"
        env:
          First_Name: Mona
