name: Running custom actions

on: [push]

jobs:
  run-custom-action: # name of the job
    runs-on: ubuntu-latest
    steps: # job steps
      - name: Run custom bash script
        run: /.github/scripts/build.sh
        shell: bash
